#!/usr/bin/env bash
set -euo pipefail

# Generates/updates a local env file with Terraform outputs + Cloud Run URL.
#
# Usage:
#   ./scripts/print_endpoints.sh [env_file]
#
# Default:
#   env/.env.dev

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="${ROOT_DIR}/infra/terraform"
TFVARS="${TF_DIR}/terraform.tfvars"
ENV_FILE="${1:-${ROOT_DIR}/env/.env.dev}"

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

tfvar_get() {
  local key="$1"
  [[ -f "${TFVARS}" ]] || return 1
  local line
  line="$(grep -E "^[[:space:]]*${key}[[:space:]]*=" "${TFVARS}" | head -n1 || true)"
  [[ -n "${line}" ]] || return 1
  echo "${line}" | sed -E 's/^[[:space:]]*[a-zA-Z0-9_]+[[:space:]]*=[[:space:]]*"([^"]*)".*$/\1/'
}

require_cmd terraform
require_cmd jq

PROJECT_ID="$(tfvar_get project_id || true)"
REGION="$(tfvar_get region || true)"
ENV_NAME="$(tfvar_get env || true)"

if [[ -z "${PROJECT_ID}" || -z "${REGION}" || -z "${ENV_NAME}" ]]; then
  echo "Missing project_id/region/env in ${TFVARS}" >&2
  exit 1
fi

mkdir -p "$(dirname "${ENV_FILE}")"

OUT_JSON="$(terraform -chdir="${TF_DIR}" output -json)"

LANDING_BUCKET="$(echo "${OUT_JSON}" | jq -r '.buckets.value.landing')"
BRONZE_BUCKET="$(echo "${OUT_JSON}" | jq -r '.buckets.value.bronze')"
QUARANTINE_BUCKET="$(echo "${OUT_JSON}" | jq -r '.buckets.value.quarantine')"
SILVER_BUCKET="$(echo "${OUT_JSON}" | jq -r '.buckets.value.silver')"
BQ_META_DATASET="$(echo "${OUT_JSON}" | jq -r '.meta_dataset.value')"
INGESTION_ROUTER_SERVICE="$(echo "${OUT_JSON}" | jq -r '.cloud_run.value.ingestion_router // ""')"
IDENTITY_API_SERVICE="$(echo "${OUT_JSON}" | jq -r '.cloud_run.value.identity_api // ""')"
API_GATEWAY_HOSTNAME="$(echo "${OUT_JSON}" | jq -r '.api_gateway.value.default_hostname // ""')"

AR_HOST="${REGION}-docker.pkg.dev"
AR_REPO="dativerso-${ENV_NAME}"

INGESTION_API_URL=""
INGESTION_API_SERVICE="$(echo "${OUT_JSON}" | jq -r '.cloud_run.value.ingestion_api // ""')"
if [[ -n "${INGESTION_API_SERVICE}" ]] && command -v gcloud >/dev/null 2>&1; then
  # gcloud returns URL in status.url
  INGESTION_API_URL="$(gcloud run services describe "${INGESTION_API_SERVICE}" \
    --project "${PROJECT_ID}" \
    --region "${REGION}" \
    --format='value(status.url)' 2>/dev/null || true)"
fi

IDENTITY_API_URL=""
if [[ -n "${IDENTITY_API_SERVICE}" ]] && command -v gcloud >/dev/null 2>&1; then
  IDENTITY_API_URL="$(gcloud run services describe "${IDENTITY_API_SERVICE}" \
    --project "${PROJECT_ID}" \
    --region "${REGION}" \
    --format='value(status.url)' 2>/dev/null || true)"
fi

cat >"${ENV_FILE}" <<EOF
# Generated by scripts/print_endpoints.sh

PROJECT_ID=${PROJECT_ID}
REGION=${REGION}
ENV=${ENV_NAME}

AR_HOST=${AR_HOST}
AR_REPO=${AR_REPO}

LANDING_BUCKET=${LANDING_BUCKET}
BRONZE_BUCKET=${BRONZE_BUCKET}
QUARANTINE_BUCKET=${QUARANTINE_BUCKET}
SILVER_BUCKET=${SILVER_BUCKET}

BQ_META_DATASET=${BQ_META_DATASET}

INGESTION_API_URL=${INGESTION_API_URL}
IDENTITY_API_URL=${IDENTITY_API_URL}
API_GATEWAY_HOSTNAME=${API_GATEWAY_HOSTNAME}
INGESTION_ROUTER_SERVICE=${INGESTION_ROUTER_SERVICE}
EOF

echo "Wrote ${ENV_FILE}"
echo "PROJECT_ID=${PROJECT_ID}"
echo "REGION=${REGION}"
echo "ENV=${ENV_NAME}"
echo "LANDING_BUCKET=${LANDING_BUCKET}"
echo "BQ_META_DATASET=${BQ_META_DATASET}"
echo "INGESTION_API_URL=${INGESTION_API_URL}"
echo "IDENTITY_API_URL=${IDENTITY_API_URL}"
if [[ -n "${API_GATEWAY_HOSTNAME}" && "${API_GATEWAY_HOSTNAME}" != "null" ]]; then
  echo "API_GATEWAY_URL=https://${API_GATEWAY_HOSTNAME}"
else
  echo "API_GATEWAY_URL="
fi
